[package]
name = "ndmsd"
version = "0.1.0"
authors = ["althypothesis <verymicrochip@gmail.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.7"
sqlite = "0.23.9"
log = "0.3.8"
simple_logger = "0.4.0"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"