[package]
name = "ndmsd"
version = "0.2.0"
authors = ["althypothesis <verymicrochip@gmail.com>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_cors = "0.2.1"
sqlite = "0.23.9"
log = "0.3.8"
simple_logger = "0.4.0"
serde = "1.0.21"
serde_derive = "1.0.21"
serde_json = "1.0.6"